services:
  webdav:
    image: efrecon/webdav-client
    security_opt:
      - apparmor:unconfined
    cap_add:
        - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - ./dav/public/:/mnt/webdrive:rshared
    healthcheck:
      test: test -f /mnt/webdrive/README.md
      interval: 5s
      timeout: 2s
      retries: 6
      start_period: 5s
    restart: unless-stopped
    devices:
      - "/dev/fuse:/dev/fuse"
  perlite:
    # image: sec77/perlite:latest
    build:
        context: ./perlite
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=public
      - HIDE_FOLDERS=docs,private,trash,lost+found
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Adriy Obsidian notes
      - SITE_TYPE=article
      - SITE_NAME=
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./dav/public:/var/www/perlite/public:rshared
    depends_on:
      webdav:
        condition: service_healthy

  perlite_web:
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 8125:80
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from: 
      - perlite
    depends_on:
      - perlite
    networks:
      - default
      - my-network

networks:
  default:
    name: perlite_default
  my-network:
    name: my-network
    external: true
